title: "Prep_Plankton_therMizer"
author: "Edited by Ezekiel Phoebe.Woodworth-Jefcoats@noaa.gov"
date: '2023-31-03'
output: html_document
---
  knitr::opts_knit$set(root.dir = "~/Mac/Dropbox/Desktop/Eastern-Scotian")
## Prep plankton forcing for input into therMizer
  
#This script uses the files output by Plankton_ts.jnl (for use with [PyFerret](https://ferret.pmel.noaa.gov/Ferret/)) to create the background resource array that will be used by therMizer.  In that script, plankton carbon densities were converted to total carbon and summed over the model domain.  This is similar to, but an improvement upon, [Woodworth-Jefcoats et al. 2019](https://www.frontiersin.org/articles/10.3389/fmars.2019.00383/full).  Here, this total carbon is used to create resource spectra at each time step.

#Notes::  Size class ranges, for reference (ESD = Equivalent Spherical Diameter):  
# - Phyto = 0.2 - 200 um ESD (mid-point size = 100.1 um ESD)  
# -	pico = 0.2 - 10 um ESD (mid-point size = 5.1 um ESD)  
# -	large (diatoms and diazotrophs) = 10 - 200 um ESD (mid-point size = 105 um ESD)  
# - Zoo = 2 - 20,00 um ESD (based on the literature)(mid-point size = 10001 um ESD)  
# -	zmicro = 2 - 200 um ESD (mid-point size = 101 um ESD)  
# -	zmeso = 200 - 20000 um ESD (mid-point size = 10100 um ESD)  
# 
# These size classes were informed by Dunne et al. [2005](https://doi.org/10.1029/2004GB002390), [2012](https://doi.org/10.1029/2010GB003935), and [2013](https://doi.org/10.1175/JCLI-D-12-00150.1), [Liu et al. 2021](https://doi.org/10.1029/2021GL094367), and [Stock et al. 2020](https://doi.org/10.1029/2019MS002043).
# 
# Conversions used:  
#   - Convert g C to gww --> $\times 10$  
#   - Convert um ESD to gww --> $\frac{4}{3}\pi(0.5\times0.0001\times size)^3$


# Load total carbon data, skipping the 6-line header
GFDL_pico <- read.csv("Ess_data/Climate forcing/gfdl-mom6-cobalt2_obsclim_phypico-vint_15arcmin_Eastern-Scotian-Shelf_monthly_1961_2010.csv", header = TRUE)
GFDL_diat <- read.csv("Ess_data/Climate forcing/gfdl-mom6-cobalt2_obsclim_phydiat-vint_15arcmin_eastern-scotian-shelf_monthly_1961_2010.csv", header = TRUE)
GFDL_diaz <- read.csv("Ess_data/Climate forcing/gfdl-mom6-cobalt2_obsclim_phydiaz-vint_15arcmin_Eastern-Scotian-Shelf_monthly_1961_2010.csv", header = TRUE)
#GFDL_pico <- read.csv("gfdl-mom6-cobalt2_obsclim_phypico-vint_60arcmin_Eastern-Scotian-Shelf_monthly_1961_2010.csv", header = TRUE)
#GFDL_diat <- read.csv("gfdl-mom6-cobalt2_obsclim_phydiat-vint_15arcmin_eastern-scotian-shelf_monthly_1961_2010.csv", header = TRUE)
#GFDL_diaz <- read.csv("gfdl-mom6-cobalt2_obsclim_phydiaz-vint_60arcmin_Eastern-Scotian-Shelf_monthly_1961_2010.csv", header = TRUE)
GFDL_zmicro <- read.csv("Ess_data/Climate forcing/gfdl-mom6-cobalt2_obsclim_zmicro-vint_15arcmin_eastern-scotian-shelf_monthly_1961_2010.csv", header = TRUE)
GFDL_zmeso <- read.csv("Ess_data/Climate forcing/gfdl-mom6-cobalt2_obsclim_zmeso-vint_15arcmin_eastern-scotian-shelf_monthly_1961_2010.csv",header = TRUE)

# Create variables for referencing the size class mid points, in gww
pico_mid <- (4/3)*pi*((0.5*0.0001*5.1)^3)
large_mid <- (4/3)*pi*((0.5*0.0001*105)^3)
micro_mid <- (4/3)*pi*((0.5*0.0001*101)^3)
meso_mid <- (4/3)*pi*((0.5*0.0001*10100)^3)

# Convert total carbon to gww and then get numerical abundance by dividing by size class mid point
# This step assumes that all plankton are the midpoint size
pico_abund <- GFDL_pico[,2]*10/pico_mid
large_abund <- (GFDL_diat[,2] + GFDL_diaz[,2])*10/large_mid
micro_abund <- GFDL_zmicro[,2]*10/micro_mid
meso_abund <- GFDL_zmeso[,2]*10/meso_mid

# Combine mid-point sizes for generating the x-axis for the linear fit
plankton_x <- log10(c(pico_mid, micro_mid, large_mid, meso_mid))

# The full spectrum sizes were generated by setting up a mizer params:
params<-readRDS("Ess_data/params_opt_calibration.RDS")

# and accessing the full size range
full_x <- log10(params@w_full)
length(full_x)
# Creating background resource for full_x, using the actual slope and intercept from the linear models.
# Create array and fill it
out_isimip <- array(numeric(), c(40,223)) # 480 time steps by 223 size classes
isimip_slope <- array(numeric(), c(40,1)) # 480 time steps
isimip_intercept <- array(numeric(), c(40,1)) # 480 time steps

# y values
for (t in seq(1,40,1)) {
  isimip_plankton <- log10(c(pico_abund[t], micro_abund[t], large_abund[t], meso_abund[t]))

  # Calculate slope and intercept, expand spectra for full size range
  # Linear fits
  isimip_lm <- lm(isimip_plankton ~ plankton_x)
  
  # Expand to full size range
  #out_isimip[t,] <- isimip_lm$coefficients[2] * full_x + isimip_lm$coefficients[1]
  out_isimip[t,] <- isimip_lm$coefficients[2]*1.03 * full_x + isimip_lm$coefficients[1]*0.85
  # The scaling for the slope and intercept were determined following the method in 
  # Woodworth-Jefcoats et al. (2019)  More information is provided below.
  
  # Save slope and intercept, for diagnostics
  isimip_intercept[t,1] <- isimip_lm$coefficients[1]
  isimip_slope[t,1] <- isimip_lm$coefficients[2]
  
}

# Save
write.table(out_isimip, file = "Ess_data/ESS_resource_spectra_S1.03I0.85.dat", quote = FALSE, row.names = TRUE, col.names = TRUE)
write.table(isimip_slope, file = "Ess_data/ESS_resource_slope_S1.03I0.85.dat", quote = FALSE, sep = "\t", row.names = FALSE, col.names = FALSE)
write.table(isimip_intercept, file = "Ess_data/ESS_resource_intercept_S1.03I0.85.dat", quote = FALSE, sep = "\t", row.names = FALSE, col.names = FALSE)
